### ISSUE TITLE
NPE in ResolverResult.java:33

### ISSUE THREAD

**Issue by iNPUTmice** [rtreffer/minidns#64] opened 2017-07-10 10:27 UTC
```
java.lang.NullPointerException: Attempt to read from field 'de.measite.minidns.DNSMessage$RESPONSE_CODE de.measite.minidns.DNSMessage.responseCode' on a null object reference
	at de.measite.minidns.hla.ResolverResult.<init>(ResolverResult.java:33)
	at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:46)
	at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:40)
	at eu.siacs.conversations.utils.Resolver.resolveWithFallback(Resolver.java:134)
	at eu.siacs.conversations.utils.Resolver.resolveFallback(Resolver.java:108)
	at eu.siacs.conversations.utils.Resolver.resolveFallback(Resolver.java:116)
	at eu.siacs.conversations.utils.Resolver.resolve(Resolver.java:60)
	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:355)
	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:501)
	at java.lang.Thread.run(Thread.java:762)
```

Here is [Resolver.java:134](https://github.com/siacs/Conversations/blob/a1f9f5e7742f1088a7b9c2dd2b4e01012f1dcb1d/src/main/java/eu/siacs/conversations/utils/Resolver.java#L134) in the version that created this stack trace. (Current master has work around).

**Comment by Flowdalic** [comment] 2017-07-12 13:53
Duplicate of #53

As soon as #63 is fixed, we should release 0.2.1.

**Closed by Flowdalic** 2017-07-12 13:53 UTC
